name: main
on: [push]

jobs:

  uas-test:
    runs-on: ubuntu-20.04
    name: UAS CYPRESS
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run --prefix cypress/integration
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
